name: Push Check

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i
      - run: npm test

  check-quality:
    runs-on: ubuntu-latest
    name: Codacy Analysis CLI
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run codacy-analysis-cli
        uses: codacy/codacy-analysis-cli-action@1.0.1
        with:
          # Run with verbose output
          verbose: # optional
          # API token to retrieve your remote Codacy configuration for the project being analyzed
          project-token: # optional
          # Codacy's API URL, to retrieve your remote Codacy configuration
          codacy-api-base-url: # optional
          # Format of the output file
          format: # optional
          # Send analysis results to an output file
          output: # optional
          # The directory to be analyzed
          directory: $PWD/src
          # Number of tools to run in parallel
          parallel: # optional
          # Maximum number of issues allowed for the analysis to succeed
          max-allowed-issues: 1
          # The name of the tool to analyze the code
          tool: # optional
          # Maximum time each tool has to execute
          tool-timeout: # optional
          # Upload analysis results to Codacy
          upload: # optional
          # Fail the analysis if any tool fails to run
          fail-if-incomplete: # optional
          # Allow network access for tools
          allow-network: # optional
          # Force files to be readable by changing the permissions before running the analysis
          force-file-permissions: # optional
  
  # build:
  #   needs: [check]
  #   runs-on: ubuntu-lastest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node_version: 12
  #     - run: npm i
  #     - run: npm run minify
